<?php

namespace Social\Logins\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Laravel\Socialite\Facades\Socialite;
use Social\Logins\Models\User; 
use Illuminate\Support\Str; // For generating random password

class LinkedinController extends Controller
{
    public function redirectTolinkedin(): RedirectResponse
    {
        return Socialite::driver('linkedin')->stateless()->redirect();
    }

    public function handleLinkedinCallback(): RedirectResponse
    {
        $user = Socialite::driver('linkedin')->stateless()->user();

        $existingUser = User::where('linkedin_id', $user->id)->first();

        if ($existingUser) {
            // Log in the existing user.
            auth()->login($existingUser, true);
        } else {
            // Create a new user.
            $newUser = new User();
            $newUser->name = $user->name;
            $newUser->email = $user->email;
            $newUser->linkedin_id = $user->id;
            $newUser->password = bcrypt(Str::random()); // Set some random password
            $newUser->save();

            // Log in the new user.
            auth()->login($newUser, true);
        }

        // Redirect to url as requested by user, if empty use /dashboard page as generated by Jetstream
        return redirect()->intended('/welcome');
    }
}
